name: Sample CI Skeleton
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - uses: csviri/git-ops-actions-deploy@0.0.1
        with:
          who-to-greet: "Hello someone"
