name: Sample CI Skeleton
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - uses: csviri/git-ops-actions-deploy@0.0.3
        with:
          ops-repo-url: "https://url.to.ops.repo"
          version: "${GITHUB_SHA}"
