name: Sample CI Skeleton
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./build.sh
      - uses: csviri/git-ops-actions-propagate-version@v1
        with:
          ops-repo: csviri/git-ops-actions-sample-ops-repo
          ops-repo-token: ${{ secrets.OPS_REPO_TOKEN }}
          version: ${{ github.sha }}
          target-environment: dev



